server:
  port: 8001
mybatis:
  type-aliases-package: com/ahai/pojo
  mapper-locations: classpath*:com/ahai/dao/xml/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provid-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    hostname: localhost
info:
  app.name: springcloud-demo
  company.name: www.ahai.com
  build.version: 1.0
  build.artifactId: artifactidByshenming

